### ISSUE TITLE
codetrans converts escaped strings to binary representation

### ISSUE THREAD

**Issue by alexlehm** [vert-x3/vertx-codetrans#1] opened 2015-03-01 18:50 UTC
when using a string with a char like "\u0000" in a java example, the converted string in Javascript and groovy is the binary representation of the string (including the nul char), which is kind of inconvenient (even though it may be allowed in javascript)

https://github.com/alexlehm/docgen-issue

(named the project docgen-issue before I noticed that this is actually in codetrans)

**Comment by alexlehm** [comment] 2015-03-01 18:54
actually the problem also shows in github
https://github.com/alexlehm/docgen-issue/blob/master/src/main/asciidoc/js/index.adoc

**Comment by vietj** [comment] 2015-03-03 14:36
gonna look at it

**Comment by vietj** [comment] 2015-03-03 15:12
the issue is fixed in master.

**Closed as completed** 2015-03-23 16:25 UTC
